language: java
sudo: true

jdk:
  - oraclejdk8
  - openjdk8

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS seckill;'
  - mysql -u root seckill < SQL/seckill.sql
  - mysql -u root -e "grant all privileges on *.* to 'root'@'%' with grant option;"
  - sudo service mysql restart


env:
  - DB=mysql