language: java
sudo: true

jdk:
  - oraclejdk8
  - openjdk8


addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client


before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS seckill;'
  - mysql -u root seckill < SQL/seckill.sql
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('abc123_') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart