language: java
sudo: true

jdk:
  - oraclejdk8
  - openjdk8

services:
  - mysql

before_install:
  - mysql -u travis -e 'CREATE DATABASE IF NOT EXISTS seckill;'
  - mysql -u travis seckill < SQL/seckill.sql
  - mysql -u root -e "CREATE USER 'newmedia'@'%' IDENTIFIED BY 'abc123_';"
  - mysql -u root -e "grant all privileges on *.* to 'newmedia'@'%' with grant option;"
  - sudo service mysql restart


env:
  - DB=mysql